version: '3'
services:
  swarm-manager:
    build: .
    container_name: swarm_beat
    environment:
    - AWS_ACCESS_KEY_ID=
    - AWS_SECRET_ACCESS_KEY=
    - AWS_DEFAULT_REGION=eu-west-1
    - ENV=dev
    - DYNAMO_TABLE=eu-west-1-swarm-management
    - PRUNE_AFTER_X_HOURS=0
    - PRUNE_AFTER_X_MIN=3
    - HEARTBEAT_INTERVAL=10
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock